# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0a710c8f55bcf0358256655fb5c7dcaf70d1ea341ac8a668641aa6ab5a882051cdba44bb5be92c0652dc4e730a4e3b3b0dc85b5d7554e944ba1f9c1c4c7074a

test:
  secret_key_base: 0b17cc0f790293825a1174c46c97ff26577f127ebbd67ccf652f85917b2d2feddbf0aa8dc4f97de5d556a08a67640d0ecf2fd96504059bce4fc2bd264ad6d833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
